version: '3'

services:
  frontend:
    build:
      context: ./frontend/app-front-proyectoSept
      dockerfile: Dockerfile
    ports:
      - "4173:4173"

  backend:
    build:
      context: ./backend/app-backend-proyecto-sept
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
